version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_crud_app
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_PORT=5678
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_EXTERNAL=jsonwebtoken,zod
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_crud_app
    ports:
      - "3000:80"
    depends_on:
      - n8n
    networks:
      - app-network

volumes:
  n8n_data:

networks:
  app-network:
    driver: bridge
