version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_crud_app
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    user: node

volumes:
  n8n_data:
